window.portfolioData = {
    "site": {
        "title": "Saisandeep Chenna",
        "logo": "SS",
        "nav": [
            { "label": "Work", "id": "work" },
            { "label": "Experience", "id": "experience" },
            { "label": "Education", "id": "education" },
            { "label": "Skills", "id": "skills" },
            { "label": "Interests", "id": "hobbies" },
            { "label": "Contact", "id": "contact" }
        ],
        "socials": {
            "linkedin": "https://www.linkedin.com/in/sai-sandeep-chenna-628ab41a7",
            "github": "https://github.com/chennasaisandeep",
            "email": "mailto:saisandeep.mds2023@gmail.com"
        },
        "resume": "data/pdf/Saisandeep Chenna.pdf"
    },
    "hero": {
        "headline": "Machine Learning Engineer at HP.",
        "subheadline": "Transforming data into insights. I specialize in building impactful ML solutions, from anomaly detection to web content extraction.",
        "ctas": [
            { "label": "View Projects", "action": "work", "primary": true },
            { "label": "Contact Me", "action": "contact", "primary": false },
            { "label": "Resume", "action": "resume", "primary": false, "href": "data/pdf/Saisandeep Chenna.pdf" }
        ],
        "metrics": [
            { "label": "Months Experience", "value": "6+" },
            { "label": "Projects Delivered", "value": "3" },
            { "label": "GPA (CMI)", "value": "9.18" }
        ]
    },
    "projects": [
        {
            "id": "proj_solar",
            "title": "Solar Power Anomaly Detection",
            "role": "Lead Developer",
            "year": "2024",
            "summary": "A near real-time system to detect anomalies in solar power generation data using Neural Networks and Isolation Forests.",
            "tags": ["Python", "Anomaly Detection", "PowerBI", "Neural Networks"],
            "gradient": "from-amber-500 to-orange-600",
            "links": { "github": "#" },
            "contentBlocks": [
                { "type": "text", "title": "The Problem", "value": "Solar power generation is subject to various inefficiencies. The goal was to improve efficiency by identifying these anomalies early." },
                { "type": "text", "title": "The Solution", "value": "I developed a near real-time anomaly detection application using Isolation Forest and Autoencoders. The system integrates with Power BI for visual inspection." },
                { "type": "list", "title": "Key Tech", "items": ["Isolation Forest", "DBSCAN", "Deep Neural Networks", "Power BI"] }
            ]
        },
        {
            "id": "proj_mlp",
            "title": "MLP Classifier from Scratch",
            "role": "Individual Contributor",
            "year": "2023",
            "summary": "A binary classification model built purely in NumPy to distinguish between Besni and Kecimen raisins.",
            "tags": ["Python", "NumPy", "Deep Learning", "Mathematics"],
            "gradient": "from-blue-500 to-indigo-600",
            "links": { "github": "https://github.com/chennasaisandeep" },
            "contentBlocks": [
                { "type": "text", "title": "Overview", "value": "To understand the math of Neural Networks, I built a Multilayer Perceptron (MLP) without frameworks. This solidified my understanding of gradient descent calculus." },
                { "type": "metrics", "data": [{ "label": "Precision", "value": "90%" }, { "label": "Libraries", "value": "NumPy Only" }] }
            ]
        },
        {
            "id": "proj_covid",
            "title": "Covid-19 Effect on Air Quality",
            "role": "Researcher",
            "year": "2020",
            "summary": "Statistical analysis of air pollutant concentrations before, during, and after the Covid-19 lockdown.",
            "tags": ["Statistics", "Hypothesis Testing", "R/Python"],
            "gradient": "from-emerald-500 to-teal-600",
            "links": { "paper": "https://www.isibang.ac.in/~rsen/Stat1old/3.pdf" },
            "contentBlocks": [
                { "type": "text", "title": "Study Scope", "value": "Mentored by Prof. Rituparna Sen (ISI, Bangalore). We performed hypothesis tests to investigate if the lockdown had a statistically significant effect on pollution levels." }
            ]
        },
         {
            "id": "proj_gan",
            "title": "Synthetic Data Quality Evaluation",
            "role": "Intern",
            "year": "2023",
            "summary": "Evaluated the quality of large-scale tabular synthetic data generated by various GAN models.",
            "tags": ["GANs", "Python", "Data Quality", "Statistics"],
            "gradient": "from-purple-500 to-pink-600",
            "links": {},
            "contentBlocks": [
                { "type": "text", "title": "Objective", "value": "Validated if synthetic data generated by GANs maintained the statistical properties of the original private datasets." }
            ]
        }
    ],
    "experience": [
        {
            "id": 0,
            "company": "HP",
            "role": "Machine Learning Engineer",
            "location": "Bengaluru, Karnataka",
            "period": "Jun 2025 – Present",
            "summary": "Working as a Full-time Machine Learning Engineer.",
            "achievements": [
                "Developing scalable ML solutions.",
                "Leveraging Python, PyTorch, and cloud technologies.",
                "Collaborating with cross-functional teams to deploy models."
            ]
        },
        {
            "id": 0.5,
            "company": "HP",
            "role": "Machine Learning Engineer Intern",
            "location": "Chennai, Tamil Nadu (Remote)",
            "period": "Mar 2025 – May 2025",
            "summary": "Focused on enhancing web content extraction efficiency.",
            "achievements": [
                "Developed a comprehensive HTML readability system.",
                "Leveraged Python's readability module to extract clean main content.",
                "Optimized extraction for A4 print formatting."
            ]
        },
        {
            "id": 1,
            "company": "Shree Cement Ltd.",
            "role": "Data Scientist Intern",
            "location": "Kolkata",
            "period": "May 2024 – Jul 2024",
            "summary": "Improved solar power generation efficiency by creating a data-driven anomaly detection system.",
            "achievements": [
                "Explored Isolation Forest, Local Outlier Factor, DBSCAN.",
                "Developed a near real-time anomaly detection application.",
                "Integrated pipeline with Power BI."
            ]
        },
        {
            "id": 2,
            "company": "Cloudcraftz AI",
            "role": "Data Scientist Intern",
            "location": "Kolkata",
            "period": "May 2023 – Jul 2023",
            "summary": "Worked on evaluating large-scale tabular synthetic data generated by GAN models.",
            "achievements": [
                "Evaluated GAN model quality using statistical metrics.",
                "Optimized BodhiX web application by enabling multiprocessing."
            ]
        }
    ],
    "skills": [
        { "name": "Python", "category": "Languages" },
        { "name": "TensorFlow", "category": "ML/AI" },
        {"name": "Pytorch", "category": "ML/AI"},
        {"name": "Transformers", "category": "ML/AI"},
        { "name": "SQL", "category": "Data" },
        { "name": "NumPy", "category": "Data" },
        { "name": "Pandas", "category": "Data" },
        { "name": "Probability", "category": "Math" },
        { "name": "Statistics", "category": "Math" },
        { "name": "Calculus", "category": "Math" },
        { "name": "OpenCV", "category": "Vision" },
        { "name": "Git", "category": "Tools" },
        { "name": "Docker", "category": "Tools" },
        { "name": "Power BI", "category": "Tools" }
    ],
    "education": [
        {
            "school": "Chennai Mathematical Institute",
            "degree": "M.Sc. Data Science",
            "year": "Aug 2023 - Apr 2025",
            "grade": "GPA: 9.18",
            "icon": "fa-graduation-cap"
        },
        {
            "school": "Indian Statistical Institute",
            "degree": "B.Math (Hons.)",
            "year": "July 2019 - May 2022",
            "grade": "77% (First Div)",
            "icon": "fa-university"
        }
    ],
    "certificates": [
        {
            "name": "Google Data Analytics Professional",
            "issuer": "Google (Coursera)",
            "description": "Comprehensive program covering data fundamentals, preparation, processing, and analysis.",
            "icon": "fab fa-google",
            "link": "https://www.coursera.org/account/accomplishments/professional-cert/PJDUC7GM2YW7"
        },
        {
            "name": "Complete Data Science Bootcamp",
            "issuer": "Udemy",
            "description": "End-to-end data science training including classification, regression, clustering, and DL.",
            "icon": "fas fa-certificate",
            "images": [
                "https://udemy-certificate.s3.amazonaws.com/image/UC-63128b89-958c-43ea-a363-92aa011fbcc2.jpg?v=1654781806000"
            ],
            "link": "https://www.udemy.com/certificate/UC-63128b89-958c-43ea-a363-92aa011fbcc2/"
        },
        {
            "name": "Tensorflow for Deep Learning Bootcamp",
            "issuer": "Udemy",
            "description": "Comprehensive TensorFlow 2 mastery covering Neural Networks, CNNs, RNNs, NLP, Computer Vision, Transfer Learning, and Time Series.",
            "icon": "fas fa-brain",
            "images": [
                "https://udemy-certificate.s3.amazonaws.com/image/UC-e6b0542b-58a1-4ea7-8ef0-80f58ddb8ac1.jpg?v=1765541464000"
            ],
            "link": "https://www.udemy.com/certificate/UC-e6b0542b-58a1-4ea7-8ef0-80f58ddb8ac1/"
        },
        {
            "name": "Complete Python Pro Bootcamp",
            "issuer": "Udemy",
            "description": "Advanced Python programming concepts and best practices.",
            "icon": "fab fa-python",
            "images": [
                "https://udemy-certificate.s3.amazonaws.com/image/UC-fd0b1ffa-4d87-41b1-af4b-f750aa13dbe1.jpg"
            ],
            "link": "https://www.udemy.com/certificate/UC-fd0b1ffa-4d87-41b1-af4b-f750aa13dbe1/"
        }
    ],
    "hobbies": [
        {
            "name": "Photography & Editing",
            "description": "I love capturing moments and bringing them to life through creative editing.",
            "icon": "fa-camera",
            "gallery": [
                "images/photography/1.jpg", "images/photography/2.jpg", "images/photography/3.jpg",
                "images/photography/4.jpg", "images/photography/5.jpg", "images/photography/6.jpg"
            ]
        },
        {
            "name": "CGI & VFX",
            "description": "Creating 3D graphics and visual effects using Blender 3D and After Effects.",
            "icon": "fa-cube",
            "gallery": [
                "images/renders/7.jpg", "images/renders/8.jpg", "images/renders/9.jpg",
                "images/renders/10.jpg", "images/renders/11.jpg"
            ]
        },
        {
            "name": "Drawing",
            "description": "Passionate about anamorphic art and perspective manipulation.",
            "icon": "fa-paint-brush",
            "gallery": [
                "images/drawings/12.jpg", "images/drawings/13.jpg", "images/drawings/14.jpg",
                "images/drawings/15.jpg", "images/drawings/16.jpg"
            ]
        },
        {
            "name": "Music",
            "description": "Music is my stress buster. I enjoy exploring different genres and discovering new artists.",
            "icon": "fa-music",
            "playlists": {
                "English": [
                    { "title": "Perfect", "artist": "Ed Sheeran", "link": "https://www.youtube.com/watch?v=2Vv-BfVoq4g" },
                    { "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "link": "https://www.youtube.com/watch?v=OPf0YbXqDm0" },
                    { "title": "Until I Found You", "artist": "Stephen Sanchez & Em Beihold", "link": "https://www.youtube.com/watch?v=hWCZP3MXdkE" },
                    { "title": "Shape of You", "artist": "Ed Sheeran", "link": "https://www.youtube.com/watch?v=JGwWNGJdvx8" },
                    { "title": "Blinding Lights", "artist": "The Weeknd", "link": "https://www.youtube.com/watch?v=4NRXx6U8ABQ" }
                ],
                "Telugu": [
                    { "title": "Hukum", "artist": "Anirudh Ravichander", "link": "https://www.youtube.com/watch?v=u2CpHdkz-bs" },
                    { "title": "Samajavaragamana", "artist": "Sid Sriram", "link": "https://www.youtube.com/watch?v=VwjbJEdYT4s" },
                    { "title": "Naatu Naatu", "artist": "Rahul Sipligunj, Kaala Bhairava", "link": "https://www.youtube.com/watch?v=OsU0CGZoV8E" },
                    { "title": "Butta Bomma", "artist": "Armaan Malik", "link": "https://www.youtube.com/watch?v=q7P9AJi0P3E" },
                    { "title": "Oo Antava", "artist": "Indravathi Chauhan", "link": "https://www.youtube.com/watch?v=LB7D36n_xCw" }
                ],
                "Hindi": [
                    { "title": "Kesariya", "artist": "Arijit Singh", "link": "https://www.youtube.com/watch?v=bZIp90pC00E" },
                    { "title": "Apna Bana Le", "artist": "Arijit Singh", "link": "https://www.youtube.com/watch?v=BddP6PYo2gs" },
                    { "title": "Tum Hi Ho", "artist": "Arijit Singh", "link": "https://www.youtube.com/watch?v=Umqb9KENgmk" },
                    { "title": "Raabta", "artist": "Arijit Singh", "link": "https://www.youtube.com/watch?v=Hx4Df7JsHWI" },
                    { "title": "Channa Mereya", "artist": "Arijit Singh", "link": "https://www.youtube.com/watch?v=bzSTpdcs-EA" }
                ],
                "Others": [
                    { "title": "Telepatía", "artist": "Kali Uchis", "link": "https://www.youtube.com/watch?v=bn_p95HbHoQ" },
                    { "title": "Comment Allez-Vous?", "artist": "Leslie Clio", "link": "https://www.youtube.com/watch?v=tKhEnC9YSd4" },
                    { "title": "Despacito", "artist": "Luis Fonsi", "link": "https://www.youtube.com/watch?v=kJQP7kiw5Fk" },
                    { "title": "Con Altura", "artist": "ROSALÍA & J Balvin", "link": "https://www.youtube.com/watch?v=p7bfOZek9t4" }
                ]
            }
        },
        {
            "name": "Fast Typing",
            "description": "Achieved typing speed of 67 WPM to boost coding productivity.",
            "icon": "fa-keyboard"
        }
    ]
};
